apiVersion: apps/v1
kind: Deployment
metadata:
  name: i211205-frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend 
    spec:
      containers:
      - name: frontend
        image: basitnazir/scdfinal-frontend:latest
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: i211205-frontend-service
spec:
  selector:
    app: frontend 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 1205
    targetPort: 80
