apiVersion: apps/v1
kind: Deployment
metadata:
  name: i211205-event-bus-deployment
  labels:
    app: event-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: event-bus-server
        image: basitnazir/scdfinal-event-bus:latest
        ports:
        - containerPort: 3214
---

apiVersion: v1
kind: Service
metadata:
  name: i211205-event-bus-service
spec:
  selector:
    app: event-bus
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3214
    targetPort: 3214