apiVersion: apps/v1
kind: Deployment
metadata:
  name: i211205-auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-server
        image: basitnazir/scdfinal-auth:latest
        ports:
        - containerPort: 3205
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3205
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3205
          initialDelaySeconds: 30
          periodSeconds: 10
---

apiVersion: v1
kind: Service
metadata:
  name: i211205-auth-service
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3205
    targetPort: 3205
