apiVersion: apps/v1
kind: Deployment
metadata:
  name: i211205-post-deployment
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post-server
        image: basitnazir/scdfinal-post:latest
        ports:
        - containerPort: 3207
---

apiVersion: v1
kind: Service
metadata:
  name: i211205-post-service
spec:
  selector:
    app: post
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3207
    targetPort: 3207